FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/QuizBuilder.Presentation/QuizBuilder.Presentation.csproj", "src/QuizBuilder.Presentation/"]
RUN dotnet restore "src/QuizBuilder.Presentation/QuizBuilder.Presentation.csproj"
COPY . .
WORKDIR "/src/src/QuizBuilder.Presentation"
RUN dotnet build "QuizBuilder.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "QuizBuilder.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "QuizBuilder.Presentation.dll"]
